### PR TITLE
@natim review.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Review by sebastienbarbier — APPROVED** [review]

**Comment by sebastienbarbier** [comment]
😍

**Review by niwo — COMMENTED** [review]
There are two options here I see:
1. Abort the startup when no key is defined, like you suggested
2. Autogenerate the key in order to make the setup working with no additional configuration and point out in the documentation that this configuration (beside other, like SMTP settings) need to be provided for production.

I would probably go for 2. as this would also facilitate testing, where you wouldn't need to hardcode a SECRET_KEY for CI/CD.

**Comment by Natim** [comment]
The third option is to use a fixed value in the docker-compose.yml and fail if the docker image runs without a SECRET_KEY. I would avoid generating the SECRET_KEY automatically because it will create bugs hard to debug.

While it is really unlikely that people will use docker-compose in production.

**Comment by niwo** [comment]
@Natim Right, this would be the simplest approach. I would suggest then to add stupid key like `SECRET_KEY=CHANGE-ME-PLEASE!` in order to make it clear that this thing has to be changed.

**Pull request merged**
